Rails/blog/config/routes.rb
Rails.application.routes.draw do

   resources :articles

  root 'welcome#index'
end

Rails/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rails/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end
  def create
    render plain: params[:article].inspect
  end
end

Rails/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Rails/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Rails/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Rails/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>

<%= form_for :article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

Rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Rails/blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p></p>